### ISSUE TITLE
[permanent] ToDo list

### ISSUE THREAD

**Issue by mafrahm** [uhh-cms/hh2bbww#9]
This issue is thought of as a common place for listing all the important next steps of the analysis.

- [ ] fix DNN (see #7)
- [ ] fix scale and pdf weights (see #8)
- [ ] plot some gen level features (@apaasch)
- [ ] Inference model / datacard writer (@mafrahm)
- [ ] Scale factors + uncertainties (e/mu ID, iso, trigger, BTag SF)
- [ ] Rebinning of variables (flat in background / flat in signal)
- [ ] Comparison to Run2 results

**Comment by mschrode** [comment]
Hi @mafrahm @Lara813 , I restructured the list a bit and added a few points. Please have a look if it makes sense
